export const gallery = [
    {
        id: 1,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-post/client/src/img/orchid-flower.jpg?raw=true",
        link: "",
        name: "Orchid",
        description: "Orchids are beatiful...",
    },
    {
        id: 2,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/bougainvillea-flower.jpg?raw=true",
        link: "",
        name: "Bougainvillea",
        description: "These flowers are the best...",
    },
    {
        id: 3,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/rosemary.jpg?raw=true",
        name: "Rosemary",
        description: "Rosemary smells like Christmas..",
    },
    {
        id: 4,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/jade-plant.jpg?raw=true",
        name: "Jade",
        description: "Jade plants are super easy...",
    },
    {
        id: 5,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/lavender.jpg?raw=true",
        name: "Lavender",
        description: "Lavender, sometimes considered...",
    },
    {
        id: 6,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/clotilde-soupert-antique-rose.jpg?raw=true",
        name: "Clotilde Soupert",
        description: "This beatiful rose...",
    },
    {
        id: 7,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/buttercup-flower.jpg?raw=true",
        name: "Buttercup",
        description: "This small flower brings...",
    },
    {
        id: 8,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/thyme.jpg?raw=true",
        name: "Thyme",
        description: "Thyme is great for cooking...",
    },
    {
        id: 9,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/philodendron-plant.jpg?raw=true",
        name: "Philodendron",
        description: "This plant is a very bright...",
    },
    {
        id: 10,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/flower-thoughts/client/src/img/mouse-ear-flower.jpg?raw=true",
        name: "Coreopsis, Mouse-Ear",
        description: "My favorite of the...",
    },
    {
        id: 11,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/marigolds.jpg?raw=true",
        name: "Marigold",
        description: "",
    },
    {
        id: 12,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/brown-eyed-susans.jpg?raw=true",
        name: "Brown Eyed Susan",
        description: "",
    },
    {
        id: 13,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/pink-flower.jpg?raw=true",
        name: "Pink Flower",
        description: "",
    },
    {
        id: 14,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/spiky-yellow-flower.jpg?raw=true",
        name: "Succulent Flower",
        description: "",
    },
    {
        id: 15,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/milk-thistle.jpg?raw=true",
        name: "Milk Thistle",
        description: "",
    },
    {
        id: 16,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/berries.jpg?raw=true",
        name: "Berries",
        description: "",
    },
    {
        id: 17,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/tall-succulent.jpg?raw=true",
        name: "Tall Succulent",
        description: "",
    },
    {
        id: 18,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/flowerpot-shelf.jpg?raw=true",
        name: "Flowerpot Shelf (Various)",
        description: "",
    },
    {
        id: 19,
        img: "https://github.com/felipezintzun/flower-power/blob/feature/judy2/client/src/img/succulent-flower.jpg?raw=true",
        name: "Succulent flower",
        description: "",
    },


    ];